services:
  postgres:
    image: postgres:17-alpine
    container_name: job-tracker-db
    environment:
      POSTGRES_DB: job_tracker
      POSTGRES_USER: job_tracker_user
      POSTGRES_PASSWORD: job_tracker_user
    ports:
      - "5432:5432"
    volumes:
      - job-tracker-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U job_tracker_user -d job_tracker"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  job-tracker-pgdata:

  #services:
  #  postgres:
  #    image: 'postgres:latest'
  #    environment:
  #      - 'POSTGRES_DB=mydatabase'
  #      - 'POSTGRES_PASSWORD=secret'
  #      - 'POSTGRES_USER=myuser'
  #    ports:
  #      - '5432'